name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  
  release:
    types: [created] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git user
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Create and switch to gh-pages
      run: |
        git checkout -B gh-pages  

    - name: Copy files to gh-pages
      run: |
        mkdir -p en ru  
        cp -r en/index.html en/  
        cp -r ru/index.html ru/  
        cp index.html index.html  

    - name: Add and commit changes
      run: |
        git add .
        git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"

    - name: Push changes to gh-pages
      run: |
        git push origin gh-pages --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
